name: marketmaking-lobster
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0=h6a678d5_0
  - arrow-cpp=19.0.0
  - aws-c-auth=0.8.5
  - aws-c-cal=0.8.5
  - aws-c-common=0.11.1
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.3
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.11
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.528
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.9.9
  - cairo=1.16.0
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - expat=2.7.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - gflags=2.2.2
  - glog=0.5.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcups=2.4.2
  - libcurl=8.14.1
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libllvm15=15.0.7
  - libnghttp2=1.57.0
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mesalib=25.1.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.18
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - pthread-stubs=0.3
  - pyarrow=19.0.0
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2=2024.07.02
  - readline=8.2
  - s2n=1.5.14
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.1
  - spirv-tools=2025.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.5.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=15.1.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - beautifulsoup4==4.14.2
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - curl-cffi==0.13.0
      - frozendict==2.4.6
      - idna==3.11
      - multitasking==0.0.12
      - peewee==3.18.3
      - protobuf==6.33.0
      - pycparser==2.23
      - requests==2.32.5
      - soupsieve==2.8
      - urllib3==2.5.0
      - websockets==15.0.1
      - yfinance==0.2.66
